/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (DominoRecomp)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80047E64u
#define func_80047E64 BootEntry  /* alias */
